// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4Mc9Gm6uA16mmyMXQ9UlUvs-627jBZc',
    appId: '1:814575891436:web:7b2f5b0766f1712c0046c9',
    messagingSenderId: '814575891436',
    projectId: 'betterself-595dd',
    authDomain: 'betterself-595dd.firebaseapp.com',
    databaseURL: 'https://betterself-595dd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'betterself-595dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyEDMXlak99G9Fckhp6biz4-L5maaOhzE',
    appId: '1:814575891436:android:03fbb3befa9f62b70046c9',
    messagingSenderId: '814575891436',
    projectId: 'betterself-595dd',
    databaseURL: 'https://betterself-595dd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'betterself-595dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARQPG1H5241EpVOkjbPEDEH2ONYzFZFac',
    appId: '1:814575891436:ios:d49f1d696ab7eb2b0046c9',
    messagingSenderId: '814575891436',
    projectId: 'betterself-595dd',
    databaseURL: 'https://betterself-595dd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'betterself-595dd.appspot.com',
    iosBundleId: 'com.example.betterself',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARQPG1H5241EpVOkjbPEDEH2ONYzFZFac',
    appId: '1:814575891436:ios:d49f1d696ab7eb2b0046c9',
    messagingSenderId: '814575891436',
    projectId: 'betterself-595dd',
    databaseURL: 'https://betterself-595dd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'betterself-595dd.appspot.com',
    iosBundleId: 'com.example.betterself',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS4Mc9Gm6uA16mmyMXQ9UlUvs-627jBZc',
    appId: '1:814575891436:web:7f02e8e418383eec0046c9',
    messagingSenderId: '814575891436',
    projectId: 'betterself-595dd',
    authDomain: 'betterself-595dd.firebaseapp.com',
    databaseURL: 'https://betterself-595dd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'betterself-595dd.appspot.com',
  );
}
